### ISSUE TITLE
Docker build command for base container does not work

### ISSUE THREAD

**Issue by shubhamkarande13** [moja-global/FLINT#73]
**Describe the bug**
The commands to build the containers as given the **Docker for Ubuntu 18:04** section do not work properly due to an error in the Dockerfiles. Using the **develop** branch.

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone the repo to your local directory and change to **FLINT/Docker**
`cd FLINT\Docker`

2. Run the command
```
# working from the examples folder "flint/tree/master/Examples/docker"
# build the base
docker build -f Dockerfile.base.ubuntu.18.04 --build-arg NUM_CPU=4 -t moja/baseimage:ubuntu-18.04 .
```

3. It will give this error in the output 

```
#8 64.43 -- Configuring done
#8 65.02 -- Generating done
#8 65.04 -- Build files have been written to: /usr/local/src/cmake-3.15.0
#8 65.06 ---------------------------------------------
#8 65.06 CMake has bootstrapped.  Now run make.
#8 65.06 /bin/sh: 1: .4: not found
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.tar.gz     && tar xzf cmake-${CMAKE_VERSION}.tar.gz     && cd cmake-${CMAKE_VERSION}     && ./bootstrap --system-curl --parallel=$NUM_CPU     && .$NUM_CPU      && make --quiet install  && make clean     && cd ..]: runc did not terminate sucessfully

C:\Development\moja-global\FLINT\Docker>
```

**Expected behaviour**
Expecting the base image to be built successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/13800316/101074480-ca5fba00-35c6-11eb-83ad-80132f36f758.png)

**Comment by gmajan** [comment]
@mfellows would you have time to have a look at this issue? It is coming back in a few user installations. thank you

**Comment by mfellows** [comment]
This is the offending command (part of that cmake setup script):
&& .$NUM_CPU

Fixed and pushed - @shubhamkarande13 could you please pull the latest develop and try again, and close this issue if it works now?

**Comment by shubhamkarande13** [comment]
@mfellows I am still getting the same error.
There is a similar issue with the **Dockerfile.flint.ubuntu.18.04** Dockerfile as well. I have fixed the errors and tested them and FLINT builds without any issues.
